UPDATE book SET title = 'The Great Talent Show Tangle' WHERE book_id = 'school_life_297_7_10' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Great Talent Show Tangle' WHERE book_id = 'school_life_297_11_14' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Great Talent Show Tangle' WHERE book_id = 'school_life_297_15_18' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Mystery of the Vanishing Lunch' WHERE book_id = 'school_life_298_7_10' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Mystery of the Vanishing Lunch' WHERE book_id = 'school_life_298_11_14' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Mystery of the Vanishing Lunch' WHERE book_id = 'school_life_298_15_18' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The BFF Band Break-Up' WHERE book_id = 'school_life_299_7_10' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The BFF Band Break-Up' WHERE book_id = 'school_life_299_11_14' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The BFF Band Break-Up' WHERE book_id = 'school_life_299_15_18' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Social Media Showdown' WHERE book_id = 'school_life_300_7_10' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Social Media Showdown' WHERE book_id = 'school_life_300_11_14' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Social Media Showdown' WHERE book_id = 'school_life_300_15_18' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Great Test Treasure Hunt' WHERE book_id = 'school_life_291_7_10' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Great Test Treasure Hunt' WHERE book_id = 'school_life_291_11_14' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Great Test Treasure Hunt' WHERE book_id = 'school_life_291_15_18' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Test of Friendship' WHERE book_id = 'school_life_292_7_10' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Test of Friendship' WHERE book_id = 'school_life_292_11_14' AND (title IS NULL OR title = '');
UPDATE book SET title = 'The Test of Friendship' WHERE book_id = 'school_life_292_15_18' AND (title IS NULL OR title = '');